### ISSUE TITLE
yaml loader issue on 

### ISSUE THREAD

**Issue by nate-johnston** [lutostag/easy2fa#2]
Hello!  I recently started using easy2fa in a Fedora Silverblue toolbox based of F36, and I get this issue when I install easy2fa (v0.8) from pip3:

```
⬢[nate@toolbox ~]$ ~/.local/bin/easy2fa
Traceback (most recent call last):
  File "/var/home/nate/.local/bin/easy2fa", line 8, in <module>
    sys.exit(main())
  File "/var/home/nate/.local/lib/python3.10/site-packages/easy2fa/__init__.py", line 249, in main
    accountStorage = AccountStorage(SHELF, account)
  File "/var/home/nate/.local/lib/python3.10/site-packages/easy2fa/__init__.py", line 63, in __init__
    self._load()
  File "/var/home/nate/.local/lib/python3.10/site-packages/easy2fa/__init__.py", line 201, in _load
    self.shelf = yaml.load(fd)
TypeError: load() missing 1 required positional argument: 'Loader'
```

Python version is 3.10, PyYAML is 6.0.  If I downgrade to PyYAML 5.4.1, then it works.  Perhaps an upper constraint is necessary until the PyYAML usage is updated.

I really appreciate the easy2fa project, it is a tremendous help to me.  Thanks!

**Comment by lutostag** [comment]
Thanks for creating the issue, PR and reaching out personally to see if this could get merged. Appreciate it. This should now be resolved. I know that some of the infrastructure for the releasing has atrophied over the years (e.g. travis-ci). I will see if I can check/move to github actions and if any other items need changing.

**Comment by nate-johnston** [comment]
Thank you very much!
